version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/dit-blog-frontend
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building frontend Docker image...
      - docker build -f frontend/Dockerfile --build-arg VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000/api} -t $REPOSITORY_URI:latest frontend
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed

env:
  variables:
    AWS_ACCOUNT_ID: "828414850187"
    AWS_DEFAULT_REGION: "eu-north-1"
    # Override this in CodeBuild environment variables to your backend URL (e.g., https://api.example.com/api)
    VITE_API_BASE_URL: "http://localhost:3000/api"
