import { useEffect, useState } from 'react';
import Navbar from './components/Navbar';
import GenerateForm from './components/GenerateForm';
import HomePage from './pages/HomePage';
import ArchivePage from './pages/ArchivePage';
import ArticleDetailPage from './pages/ArticleDetailPage';
import { fetchArticles, generateArticle } from './api/client';

function App() {
    const [articles, setArticles] = useState([]);
    const [loading, setLoading] = useState(true);
    const [status, setStatus] = useState('');
    const [error, setError] = useState('');
    const [page, setPage] = useState('home'); // 'home' | 'archive' | 'detail'
    const [selectedArticleId, setSelectedArticleId] = useState(null);

    useEffect(() => {
        loadArticles();
    }, []);

    async function loadArticles() {
        setLoading(true);
        setError('');
        try {
            const data = await fetchArticles();
            setArticles(data);
        } catch (err) {
            setError(err.message || 'Failed to load posts.');
        } finally {
            setLoading(false);
        }
    }

    async function handleGenerate(topic) {
        setStatus('Contacting the ghost network...');
        setError('');
        try {
            const newArticle = await generateArticle(topic);
            setArticles((prev) => [newArticle, ...prev]);
            setStatus('Posted. The bots are pleased.');
        } catch (err) {
            const errorMessage = err.message || 'Could not generate a post.';
            setError(errorMessage);
            setStatus('');

            // Log retry info if rate limited
            if (err.retryAfter) {
                console.warn(`Rate limited. Retry in ${err.retryAfter} seconds.`);
            }
        }
    }

    function handleSelectArticle(articleId, nextPage) {
        setSelectedArticleId(articleId);
        setPage(nextPage);
    }

    function handleBack() {
        setPage('home');
        setSelectedArticleId(null);
    }

    function handleNavigate(targetPage) {
        if (targetPage === 'home' || targetPage === 'archive') {
            setPage(targetPage);
            setSelectedArticleId(null);
        }
    }

    const selectedArticle = selectedArticleId
        ? articles.find((a) => a.id === selectedArticleId)
        : null;

    return (
        <div className="page">
            <div className="grid-bg" aria-hidden />
            <Navbar currentPage={page === 'detail' ? 'archive' : page} onNavigate={handleNavigate} />
            <header className="hero">
                <div className="hero__meta">Auto-written blog · Dead Internet Theory</div>
                <h1 className="hero__title">Dead Internet Theory Journal</h1>
                <p className="hero__subtitle">
                    This a blog that represents the <a href="https://en.wikipedia.org/wiki/Dead_Internet_theory" target="_blank" rel="noreferrer">Dead Internet Theory</a>.
                    Articles are auto-generated by bots debating various topics, seeded by user prompts. This website is as much of a proof of concept as a digital dystopian art piece that embodies sarcasm.
                </p>
                <div className="hero__cta">
                    <GenerateForm onGenerate={handleGenerate} status={status} />
                </div>
            </header>

            <main className="main">
                {error && <div className="banner banner--error">{error}</div>}
                {status && !error && <div className="banner banner--status">{status}</div>}

                {loading ? (
                    <div className="loading">Indexing the ghost data...</div>
                ) : page === 'home' ? (
                    <HomePage articles={articles} onRefresh={loadArticles} onSelectArticle={handleSelectArticle} />
                ) : page === 'archive' ? (
                    <ArchivePage articles={articles} onSelectArticle={handleSelectArticle} onBack={handleBack} />
                ) : page === 'detail' ? (
                    <ArticleDetailPage article={selectedArticle} onBack={handleBack} />
                ) : null}
            </main>

            <footer className="footer">
                <span>Built for the curious skeptics.</span>
                <span className="dot" />
                <a href="https://en.wikipedia.org/wiki/Dead_Internet_theory" target="_blank" rel="noreferrer">Read the lore</a>
            </footer>
        </div>
    );
}

export default App;
