// Root application component for the frontend SPA.
// Manages navigation between views and orchestrates data fetching
// and article generation via the API client.
import { useEffect, useState } from 'react';
import Navbar from './components/Navbar';
import GenerateForm from './components/GenerateForm';
import HomePage from './pages/HomePage';
import ArchivePage from './pages/ArchivePage';
import ArticleDetailPage from './pages/ArticleDetailPage';
import { fetchArticles, generateArticle } from './api/client';

function App() {
    // State: list of articles loaded from backend
    const [articles, setArticles] = useState([]);
    // State: global loading flag for initial fetch and refreshes
    const [loading, setLoading] = useState(true);
    // State: transient status messages (success/info)
    const [status, setStatus] = useState('');
    // State: error banner message from failed operations
    const [error, setError] = useState('');
    // State: current view. One of: 'home' | 'archive' | 'detail'
    const [page, setPage] = useState('home'); // 'home' | 'archive' | 'detail'
    // State: selected article id used by detail view
    const [selectedArticleId, setSelectedArticleId] = useState(null);

    useEffect(() => {
        loadArticles();
    }, []);

    /**
     * Fetch latest articles from the backend API.
     * Updates loading & error states accordingly.
     */
    async function loadArticles() {
        setLoading(true);
        setError('');
        try {
            const data = await fetchArticles();
            setArticles(data);
        } catch (err) {
            setError(err.message || 'Failed to load posts.');
        } finally {
            setLoading(false);
        }
    }

    /**
     * Generate a new article from a topic using the backend AI service.
     * Prepends the created article to the current list and surfaces
     * status or error messages to the user.
     */
    async function handleGenerate(topic) {
        setStatus('Contacting the ghost network...');
        setError('');
        try {
            const newArticle = await generateArticle(topic);
            setArticles((prev) => [newArticle, ...prev]);
            setStatus('Posted. The bots are pleased.');
        } catch (err) {
            const errorMessage = err.message || 'Could not generate a post.';
            setError(errorMessage);
            setStatus('');

            // Log retry info if rate limited
            if (err.retryAfter) {
                console.warn(`Rate limited. Retry in ${err.retryAfter} seconds.`);
            }
        }
    }

    /**
     * Navigate to a specific article and set the target page.
     */
    function handleSelectArticle(articleId, nextPage) {
        setSelectedArticleId(articleId);
        setPage(nextPage);
    }

    /**
     * Navigate back to the home view and clear selection.
     */
    function handleBack() {
        setPage('home');
        setSelectedArticleId(null);
    }

    /**
     * Handle top-level navigation between Home and Archive.
     * Resets selected article when switching views.
     */
    function handleNavigate(targetPage) {
        if (targetPage === 'home' || targetPage === 'archive') {
            setPage(targetPage);
            setSelectedArticleId(null);
        }
    }

    // Derived: the currently selected article (for detail view)
    const selectedArticle = selectedArticleId
        ? articles.find((a) => a.id === selectedArticleId)
        : null;

    return (
        <div className="page">
            {/* Decorative grid background */}
            <div className="grid-bg" aria-hidden />
            {/* Global navigation bar with simple view switching */}
            <Navbar currentPage={page === 'detail' ? 'archive' : page} onNavigate={handleNavigate} />
            <header className="hero">
                <div className="hero__meta">Auto-written by AI · Dead Internet Theory Blog</div>
                <h1 className="hero__title">Dead Internet Theory Blog</h1>
                <p className="hero__subtitle">
                    This a journal that represents the <a href="https://en.wikipedia.org/wiki/Dead_Internet_theory" target="_blank" rel="noreferrer">Dead Internet Theory</a>.
                    Articles are auto-generated by AI debating various topics, seeded by user prompts. This website is as much of a proof of concept as a digital dystopian art piece that embodies sarcasm.
                </p>
                <div className="hero__cta">
                    {/* Prompt form to create new AI-generated article */}
                    <GenerateForm onGenerate={handleGenerate} status={status} />
                </div>
            </header>

            <main className="main">
                {/* Global banners for errors and transient status */}
                {error && <div className="banner banner--error">{error}</div>}
                {status && !error && <div className="banner banner--status">{status}</div>}

                {loading ? (
                    // Initial loading indicator
                    <div className="loading">Indexing the ghost data...</div>
                ) : page === 'home' ? (
                    // Latest articles with refresh and drill-down
                    <HomePage articles={articles} onRefresh={loadArticles} onSelectArticle={handleSelectArticle} />
                ) : page === 'archive' ? (
                    // Archive list of all articles
                    <ArchivePage articles={articles} onSelectArticle={handleSelectArticle} onBack={handleBack} />
                ) : page === 'detail' ? (
                    // Detailed view of a single article
                    <ArticleDetailPage article={selectedArticle} onBack={handleBack} />
                ) : null}
            </main>

            <footer className="footer">
                <span>Built for the curious skeptics.</span>
                <span className="dot" />
                <a href="https://en.wikipedia.org/wiki/Dead_Internet_theory" target="_blank" rel="noreferrer">Read the lore</a>
            </footer>
        </div>
    );
}

export default App;
